EVAL_FUNCTION_ID_KEY = "eval_function_id"
ID_KEY = "id"
THRESHOLD_COMPARISON_KEY = "threshold_comparison"
THRESHOLD_KEY = "threshold"
UNIT_TEST_ID_KEY = "unit_test_id"
UNIT_TEST_NAME_KEY = "unit_test_name"
