ENDPOINT_PATH = "endpoints"
MODEL_BUNDLE_SIGNED_URL_PATH = "model_bundle_upload"
ASYNC_TASK_PATH = "task_async"
ASYNC_TASK_RESULT_PATH = "task/result"
SYNC_TASK_PATH = "task_sync"
SCALE_DEPLOY_ENDPOINT = "https://api.scale.com/v1/hosted_inference"
